version: '3.8'
services:
  rolla-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rolla-api
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - rolla-mysql
    env_file:
      - .env

  rolla-mysql:
    image: mysql:8
    container_name: rolla-mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - rolla-mysql:/var/lib/mysql

volumes:
  rolla-mysql:
    name: rolla-mysql-db
